#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|task|release|hotfix\rs)\/.*RSWEB.*$"

message="There is something wrong with your branch name. Your commit will be rejected. You should rename your branch like $valid_branch_regex and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
