# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ed6b01b51fcf887b274ed1cf9208660e68bd61172c16ea7469c7fae34050dbc79a0a3dcc3a0fcd516415bb8bb3d592074fbeec1693d342995564d2cc2269907

test:
  secret_key_base: 09d06a16bf692540001a0218956601c9c7ef319be562f5a684c7ecdf74e1e5150bf68ef548898f8d4eda03000a57c04e7a8d4277e99077d73e56fd840cecd0f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
